#!/usr/bin/env bash
# Lefthook commit-msg check. Usage: check-commit-msg.sh <commit-msg-file>
set -euo pipefail

if [[ $# -lt 1 || -z "${1}" ]]; then
  echo "Usage: $0 <commit-msg-file>" >&2
  exit 1
fi

msg_file=$1
if [[ ! -f "${msg_file}" ]]; then
  echo "error: commit message file not found: ${msg_file}" >&2
  exit 1
fi

_script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
# shellcheck source=attribution-lib.sh
. "${_script_dir}/attribution-lib.sh"

text=$(tr -d '\r' < "${msg_file}")
failed=0

co_matches=$(printf '%s\n' "${text}" | attribution_co_author_lines)
if [[ -n "${co_matches}" ]]; then
  failed=1
  echo "Commit message must not contain Co-authored-by:"
  while IFS= read -r line || [[ -n "${line}" ]]; do
    [[ -z "${line}" ]] && continue
    echo "  ${line}"
  done <<< "${co_matches}"
fi

gen_matches=$(printf '%s\n' "${text}" | attribution_generated_lines)
if [[ -n "${gen_matches}" ]]; then
  failed=1
  echo "Commit message must not contain Generated by/with, 🤖 Generated, or Assisted-by:"
  while IFS= read -r line || [[ -n "${line}" ]]; do
    [[ -z "${line}" ]] && continue
    echo "  ${line}"
  done <<< "${gen_matches}"
fi

email_matches=$(printf '%s\n' "${text}" | attribution_email_lines)
if [[ -n "${email_matches}" ]]; then
  failed=1
  echo "Commit message must not contain an email address:"
  while IFS= read -r line || [[ -n "${line}" ]]; do
    [[ -z "${line}" ]] && continue
    echo "  ${line}"
  done <<< "${email_matches}"
fi

if [[ "${failed}" -ne 0 ]]; then
  echo "CI will reject this commit even if you pass --no-verify or LEFTHOOK=0."
  echo "Edit the message, or: git rebase -i <base-sha>"
  exit 1
fi
